// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8uxTPfKH19ZWSwJoOMhpnqppqQ2_J9E',
    appId: '1:563671868242:web:8031b7443c1cd7dc9b908b',
    messagingSenderId: '563671868242',
    projectId: 'prosper-manager-95ee0',
    authDomain: 'prosper-manager-95ee0.firebaseapp.com',
    storageBucket: 'prosper-manager-95ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALRvCZBtjCdXnMJZQbE_Vh-qTHRYdzw5U',
    appId: '1:563671868242:android:cffebc2f8053b8419b908b',
    messagingSenderId: '563671868242',
    projectId: 'prosper-manager-95ee0',
    storageBucket: 'prosper-manager-95ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1R3V_g21VpU7gDm3gSilGdpGLv6iT9wM',
    appId: '1:563671868242:ios:803385924c90f7a59b908b',
    messagingSenderId: '563671868242',
    projectId: 'prosper-manager-95ee0',
    storageBucket: 'prosper-manager-95ee0.appspot.com',
    iosBundleId: 'com.example.verygoodcore.money-management-dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1R3V_g21VpU7gDm3gSilGdpGLv6iT9wM',
    appId: '1:563671868242:ios:b1be39b17941c70d9b908b',
    messagingSenderId: '563671868242',
    projectId: 'prosper-manager-95ee0',
    storageBucket: 'prosper-manager-95ee0.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD8uxTPfKH19ZWSwJoOMhpnqppqQ2_J9E',
    appId: '1:563671868242:web:239991b85806adb79b908b',
    messagingSenderId: '563671868242',
    projectId: 'prosper-manager-95ee0',
    authDomain: 'prosper-manager-95ee0.firebaseapp.com',
    storageBucket: 'prosper-manager-95ee0.appspot.com',
  );
}
